services:
  haproxy:
    networks:
      - bootnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    ports:
      - 8080:8080
      - 1963:1963

networks:
  bootnet:
    external: true